postgres: &postgres
  adapter: postgresql
  encoding: utf8
  host: localhost
  port: 45432
  username: db
  password: password
  database: demo

test:
  <<: *postgres
  database: <%= ENV['DB_NAME'] %>-test

development:
  <<: *postgres
